export const CONFIG = {
  PORT: process.env.PORT || 3000,

  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,

  SHEET_ID: process.env.GOOGLE_SHEET_ID,
  PRODUCTS_SHEET_NAME: "Products",
  DOWNLOADS_SHEET_NAME: "Downloads",

  GOOGLE_SERVICE_ACCOUNT: process.env.GOOGLE_SERVICE_ACCOUNT,

  FRONT_BASE_URL: process.env.FRONT_BASE_URL
};
